POST localhost:9000/api/tasks
Content-Type: application/json

{
  "title": "test test",
  "description": "opis"
}

###

GET localhost:9000/api/tasks

###

GET localhost:9000/api/tasks/222

###

DELETE localhost:9000/api/tasks/22

###