POST localhost:9000/api/tasks
Content-Type: application/json

{
  "id": 22,
  "author": "me",
  "title": "dokończyć lekcję"
}

###

GET localhost:9000/api/tasks

###

GET localhost:9000/api/tasks/222

###

DELETE localhost:9000/api/tasks/22

###