POST {{api}}/tasks
Content-Type: application/json

{
  "title": "test test",
  "description": "opis"
}

###

GET {{api}}/tasks

###

GET {{api}}/tasks/222

###

DELETE {{api}}/tasks/22

###

PUT {{api}}/tasks/1
Content-Type: application/json

{
  "title": "test test",
  "description": "opis"
}

###

POST {{api}}/tasks/3/tags
Content-Type: application/json

{
  "tagId": 3
}

###

DELETE {{api}}/tasks/3/tags/3